book/src/02_4_hello_board.md
book/src/03_2_cargo_generate.md

Fix: added tips by the participants

---

advanced/button-interrupt/exercise/Cargo.toml
advanced/button-interrupt/solution/Cargo.toml
advanced/i2c-driver/solution/Cargo.toml
advanced/i2c-sensor-reading/solution/Cargo.toml
common/lib/esp32-c3-dkc02-bsc/Cargo.toml
intro/hardware-check/Cargo.toml
intro/http-client/exercise/Cargo.toml
intro/http-client/solution/Cargo.toml
intro/http-server/exercise/Cargo.toml
intro/http-server/solution/Cargo.toml
intro/mqtt/exercise/Cargo.toml
intro/mqtt/solution/Cargo.toml

This change sets a fixed commit revision to the `riscv` patch annotation in all `Cargo.toml` files.
Using `master` as a `branch` option resulted in different commit hashes at different times, which occurred due to changes in the [`riscv` crate](https://github.com/rust-embedded/riscv). This crate has seen some changes in the last days / weeks that broke the current setup, therefore a working revision is set.
All examples compiled successfully but have not been tested with the hardware itself.
This should fix #55.

Use `rev` option to set fixed commit hash

---

advanced/i2c-driver/solution/src/main.rs
advanced/i2c-sensor-reading/solution/src/main.rs
advanced/i2c-sensor-reading/solution/src/main_both.rs
book/src/01_intro.md
book/src/02_0_preparations.md
book/src/02_1_hardware.md
book/src/02_2_software.md
book/src/03_2_cargo_generate.md
book/src/03_5_3_mqtt.md
book/src/04_0_advanced_workshop.md
book/src/04_2_low_level_io.md
common/lib/esp32-c3-dkc02-bsc/src/led.rs
intro/mqtt/exercise/cfg.toml.example
intro/mqtt/host-client/cfg.toml.example

This PR changes the workshop material to be explicitly for the ESP-RS board. 
(It is still possible to use the ESP32-C3-DevKitC-02. To run some of the solutions in the i2c folders it is necessary to uncomment / comment out some pins and slave addresses.)

Updates resulting from testing the ESP-RS board

---

.devcontainer/test.sh
.github/workflows/dockerimage.yml

This PR adds a Github CI workflow to build the Docker image from the `Dockerfile` in folder `.devcontainer`. It uses the resulting Docker image to compile all Rust libraries & exercises in this repository.

Add Github CI pipeline to check code

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/test.sh
.github/workflows/dockerimage.yml
book/src/02_2_software.md

This PR fixes the Github CI workflow to build the Docker image in `.devcontainer/Dockerfile`. The Docker image is now built fully, all Rust projects are compiled within the image.
Due to a few restrictions when building a [Docker image using Github Actions](https://docs.github.com/en/actions/creating-actions/dockerfile-support-for-github-actions), the `Dockerfile` has been updated to avoid issues with `USER` & `WORKDIR` instructions.
* adjust `Dockerfile` to work on Github CI & as a VS Code devcontainer
* fix VS Code devcontainer config to set workspace & user
* update Github CI workflow to build Docker image & compile Rust projects
* reduce Docker image size, use `bullseye-slim` base image, remove unnecessary packages
* update instructions in material

Fix CI pipeline & devcontainer setup

---

book/src/02_3_repository.md

The windows instructions have `git clone` twice on the commandline.

Fix an error in the windows instructions

---

common/lib/esp32-c3-dkc02-bsc/src/led.rs

The addressable LED was removed and then added back in again. To make the `button-interrupt` `main_led.rs` solution work again, the pin is changed.

Change pin number of (re-added) addressable LED.

---

advanced/button-interrupt/exercise/Cargo.toml
advanced/button-interrupt/solution/Cargo.toml
advanced/i2c-driver/solution/Cargo.toml
advanced/i2c-sensor-reading/solution/Cargo.toml
book/src/03_3_2_http_client.md
book/src/03_4_http_server.md
common/lib/esp32-c3-dkc02-bsc/Cargo.lock
common/lib/esp32-c3-dkc02-bsc/Cargo.toml
common/lib/esp32-c3-dkc02-bsc/src/wifi.rs
intro/hardware-check/Cargo.toml
intro/hardware-check/src/main.rs
intro/http-client/exercise/Cargo.toml
intro/http-client/solution/Cargo.toml
intro/http-client/solution/src/main.rs
intro/http-client/solution/src/solution1.rs
intro/http-server/exercise/Cargo.toml
intro/http-server/exercise/src/main.rs
intro/http-server/solution/Cargo.toml
intro/http-server/solution/src/main.rs
intro/mqtt/exercise/Cargo.toml
intro/mqtt/solution/Cargo.toml
intro/mqtt/solution/examples/solution1.rs
intro/mqtt/solution/src/main.rs

Minor changes:
- removed `new_with_conn`
- new_with_call back could be replace by new
- logging other output from MQTT (minor!)

Clean branch flashing and wifi connection

---

book/src/02_1_hardware.md

Added the `$ ls /dev/tty.usbmodem*` command under macOS because it works. Before it was listed under Linux but [removed there](https://github.com/ferrous-systems/espressif-trainings/commit/6d461719432a111a79612784eaaeda8167ff3074).

Fix formatting and missing command on hardware_check instructions.

---

advanced/i2c-sensor-reading/examples/part_2.rs

gyro data of axis y is printed twice, probably just a simple typo fix

Update loop to print correct data

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.gitpod.Dockerfile
.gitpod.yml
.vscode/launch.json
.vscode/tasks.json
scripts/build.sh
scripts/flash.sh
scripts/run-wokwi.sh

- Wokwi simulation: Using [wokwi-server](https://github.com/MabezDev/wokwi-server) you can simulate the projects.
- Wokwi also supports GDB debugging, so I included` launch.json` with the necessary configuration to debug the project from devcontainers (although it requires the user to set the path to the project to be debugged).
- When using devcontainers, we cant flash with `cargo-espflash` so I added [`web-flash`](https://github.com/bjoernQ/esp-web-flash-server)  to flash real devices from devcontainers!
- Add some vscode task to build, flash, and run Wokwi simualtions from devcontainers

Add wokwi simulation and web flashing support.

---

advanced/i2c-driver/Cargo.toml
advanced/i2c-sensor-reading/Cargo.toml
common/lib/esp32-c3-dkc02-bsc/Cargo.lock
common/lib/esp32-c3-dkc02-bsc/Cargo.toml
intro/hardware-check/Cargo.toml
intro/http-client/Cargo.toml
intro/http-server/Cargo.toml
intro/mqtt/exercise/Cargo.toml

As seen in #127, some of the examples were not building. As [suggested per @ashnikel](https://github.com/ferrous-systems/espressif-trainings/issues/127#issuecomment-1385523705) adding this dependency solves the issue.
Closes #127

Add `ignore` dependency

---

.github/workflows/dockerimage.yml
README.md
book/src/01_intro.md

- Removes warning message
- CI now runs daily
- Add CI badge on readme
- Fix readme links

Remove warn message

---

.devcontainer/test.sh
advanced/button-interrupt/sdkconfig.defaults
book/src/03_3_3_https_client.md
intro/hardware-check/sdkconfig.defaults
intro/http-client/examples/https_client.rs
intro/http-client/sdkconfig.defaults
intro/http-server/sdkconfig.defaults
intro/mqtt/exercise/sdkconfig.defaults

- ~~CI now updates `sdkconfig.defaults` before building HTTPS client example~~
- Removed the todo in `https_client.rs` all it needed is a `cargo clean`
- Removed certificate config from all `sdkconfig.defaults`
- https://github.com/espressif/esp-idf/issues/7631

Add https example CI check

---

book/src/02_4_hello_board.md

There was one `espmonitor` reference left in the book.

Remove `espmonitor` reference

---

README.md
advanced/button-interrupt/Cargo.toml
advanced/i2c-driver/Cargo.toml
advanced/i2c-sensor-reading/Cargo.toml
common/lib/get-uuid/Cargo.toml
common/lib/mqtt-messages/Cargo.toml
common/lib/mqtt-messages/src/lib.rs
common/lib/rgb-led/Cargo.toml
common/lib/wifi/Cargo.toml
intro/hardware-check/Cargo.toml
intro/hardware-check/src/main.rs
intro/http-client/Cargo.toml
intro/http-server/Cargo.toml
intro/http-server/examples/http_server.rs
intro/http-server/src/main.rs
intro/mqtt/exercise/Cargo.toml
intro/mqtt/exercise/examples/solution_publ.rs
intro/mqtt/exercise/examples/solution_publ_rcv.rs
intro/mqtt/exercise/src/main.rs
intro/mqtt/host-client/Cargo.toml
intro/mqtt/host-client/src/main.rs

- Remove WIP warning from README
- Format dependencies

Format dependencies

---

book/src/02_3_repository.md

While following the instructions in the book I noticed that the command to substitute the path on Windows results in an error: 
```
subst r:\ espressif-trainings
Invalid parameter - R:\
```
This PR removes the `\` in the command to make it work. Please also refer to the [Microsoft docs for subst](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/subst).

Fix subst command in book

---

book/src/03_3_3_https_client.md

It looks like this part of the tutorial wasn't updated when the example and crate were. This change should fix that.

Fix an example in a tutorial for https-client

---

common/lib/rgb-led/src/lib.rs

I wanted to "borrow" the rgb-led library for my own project, but my devboard uses pin 8.
Update rgb-led's constructor to allow the user to pass different pins (and channels).
Tested in my own project and by building the `std-training/advanced/button-interrupt` project in this repository.

Allow parameters when constructing rgb-led

---

book/src/02_3_repository.md

The folder was removed in https://github.com/esp-rs/std-training/pull/161

Remove mention to extra folder

---

intro/http-client/examples/http_client.rs
intro/http-client/examples/https_client.rs

handle the case where UTF-8 sequences are split by the chunking in the http-client examples

---

.devcontainer/Dockerfile

This would make it compatible with the latest `espflash` versions

Update base image

---

.github/workflows/ci.yml
.github/workflows/wokwi_projects.yml

Running any simulation outside the `esp-rs` org will result in failure due to the `WOKWI_CLI` token not being set

Only run Wokwi simualtions in esp-rs repos

---

book/src/01_intro.md

~~Should probably be merged after https://github.com/esp-rs/no_std-training/pull/70 and I update the book link~~ Can now be merged!

Add support note
