- LICENSE-APACHE.txt
- LICENSE-MIT.txt
- README.md
Skelton README files for each example coming next.
> Add README.md

- book/src/02_4_hello_board.md
Prevent troubleshooting with wifi with the right frequency :)
> fix: wifi 5Ghz not supported, 2.4Ghz necessary

- book/src/02_3_repository.md
Directory order in 02_3 changed alphabetically.
> fix: repository order

- book/src/03_5_2_mqtt.md
Mqtt summary corresponds to page title.
> fix: changed title

- book/src/02_2_software.md
- book/src/03_3_2_http_client.md
- book/src/03_4_http_server.md
- book/src/03_5_2_mqtt.md
- intro/hardware-check/src/main.rs
> Fix: troubleshooting tips

- book/src/04_0_advanced_workshop.md
This adds an intro text to the advanced part
> add intro text

- book/src/04_4_0_interrupts.md
- book/src/04_4_1_interrupts.md
- book/src/04_4_2_interrupts.md
This adds an actual introduction to the exercise which introduces the problem of `static mut`s  as well as more solving help
> Interrupt exercise

- book/src/02_2_software.md
> Suggest "Even Better TOML" instead of "Better TOML" extension

- book/src/01_intro.md
- book/src/02_2_software.md
> Fix botched conflict resolution.

- book/src/01_intro.md
Clarified that the board is available for purchase.
> Changed board availability

- book/src/02_2_software.md
> Crates cleanup

- book/src/02_0_preparations.md
- book/src/02_2_software.md
- book/src/02_4_hello_board.md
Tips for flashing sent by Juraj (pressing the boot button)
https://georgik.rocks/unable-to-flash-esp32-with-these-usb-c-cables/
> Added press on boot tips from Juraj

- book/src/02_2_software.md
Adressed @BriocheBerlin comment on git tag.
> changed tagged branch to git tag

- book/src/04_3_2_i2c.md
Infos on registers for the sensors specifically. Removes info about CPU registers.
As conceived by @Dajamante
> Adds info on peripheral registers, removes info for CPU registers.

- book/src/03_4_http_server.md
Reverts ferrous-systems/espressif-trainings#112
> Revert "Update 03_4_http_server.md"

- README.md
- book/src/01_intro.md
This adds a warning to book and readme, that the code resulting from following the book does not compile
> add warning

- .devcontainer/test.sh
- .github/workflows/dockerimage.yml
- intro/http-client/examples/http_client.rs
- intro/http-client/examples/https_client.rs
- intro/http-server/examples/http_server.rs
- intro/mqtt/exercise/examples/solution_publ_rcv.rs
- CI is now run in parallel
- Examples are now tested in CI
- Some examples were not building
> Improve CI and fix examples

- .devcontainer/Dockerfile
- .gitpod.Dockerfile
- advanced/button-interrupt/.cargo/config.toml
- advanced/i2c-driver/.cargo/config.toml
- advanced/i2c-sensor-reading/.cargo/config.toml
- book/src/02_2_software.md
- book/src/02_4_hello_board.md
- book/src/03_2_cargo_generate.md
- book/src/03_3_2_http_client.md
- book/src/03_3_3_https_client.md
- book/src/03_4_http_server.md
- book/src/03_5_3_mqtt.md
- book/src/04_3_1_i2c.md
- common/lib/esp32-c3-dkc02-bsc/.cargo/config.toml
- intro/hardware-check/.cargo/config.toml
- intro/hardware-check/README.md
- intro/http-client/.cargo/config.toml
- intro/http-server/.cargo/config.toml
- intro/mqtt/exercise/.cargo/config.toml
- Added `espflash`
- Added custom runner
- Cleaned some unnecessary comments 
- Add comment to explain `ESP_IDF_TOOLS_INSTALL_DIR`
- Updated the book to use the custom runner
- We should probably add a note on the book to explain the custom runner, so users do no think is magic
> Update `.cargo/config.toml` 

- .devcontainer/Dockerfile
Added cargo-generate, clippy and libssl-dev to devcontainer.
> Add cargo-generate, clippy and depdencies

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/test.sh
- .github/workflows/CI.yml
Updated the `Dockerfile`, `devcontainer.json` and CI to avoid using the docker image as `root`
> Update Dockerfile to avoid using `root`

- book/src/02_2_software.md
> Dependency typo in 02_2_software.md
